name: 'API References'

on:
    push:
        tags:
            - 'v*'

jobs:
    trigger-api-refs-build:
        name: 'Build API References'
        runs-on: ubuntu-26.04
        steps:
          - name: Generate token
            id: generate_token
            uses: actions/create-github-app-token@v3
            with:
                client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                owner: ${{ github.repository_owner }}

          - name: "Trigger API references' build"
            shell: bash
            run: |
                gh api --method POST "/repos/ibexa/documentation-developer/actions/workflows/api_refs.yaml/dispatches" \
                  -f ref="5.0" \
                  -f "inputs[version]=${{ github.ref_name }}"
            env:
                GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
